# Generated by Django 4.2.16 on 2024-10-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modelYear', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('accidental_background', models.BooleanField(default=False)),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.FloatField()),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('leftside_img', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('rightside_img', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('insurance_end_date', models.DateField()),
                ('ownership_type', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand')),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.oiltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.FloatField()),
                ('rent_car_image', models.ImageField(blank=True, null=True, upload_to='rent_car_images/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand')),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.oiltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
